pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker { image 'node:20.11.1-alpine3.19' }
            }
            stages {
                stage('checkout') {
                    steps {
                        echo "hola mundo"
                    }
                }
            }
            stages {
        stage('Instalar dependencias') {
            steps {
                // Ejecutar npm install
                sh 'npm install'
            }
        }
        stage('Ejecutar pruebas') {
            steps {
                // Ejecutar npm run test
                sh 'npm run test'
            }
        }
        stage('Construir proyecto') {
            steps {
                // Ejecutar npm run build
                sh 'npm run build'
            }
        }
        }
    }
}
